# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57548c9a75e1c0786702f6f3d70c22caf15f1adb5c41e5fb6ff486267718e3535e7e883df6b7b3f7910454d585a03e28a6b1a9177701ccc3f36d763bc4b4b4a8

test:
  secret_key_base: 7dfe51d5f0d7e8ed2bd69850c394c51933adc16b0ba437c1fb1997eaf3636f260f251e51166bec1213e1763caf48f22eebe3f858d3895028f2f507058708bbfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
